<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Project;
use Carbon\Carbon;

class ProjectsSeeder extends Seeder
{
    public function run(): void
    {
        // Clear existing projects
        Project::truncate();

        $projects = [
            // ==================== COMPLETED PROJECTS ====================

            // Featured Completed Projects
            [
                'title' => 'Building Electrical Works for Prestige IVY League',
                'slug' => 'prestige-ivy-league-electrical-works',
                'description' => 'Complete internal and external electrical works for Prestige IVY League residential project.',
                'full_description' => 'Comprehensive electrical works including internal and external electrical systems, power distribution, lighting, and safety systems for Prestige IVY League residential development in HiTec City, Hyderabad.',
                'client' => 'GVS Projects Pvt. Ltd.',
                'location' => 'HiTec City, Hyderabad',
                'category' => 'Electrical Works',
                'value' => 809.11,
                'start_date' => Carbon::parse('2020-01-15'),
                'end_date' => Carbon::parse('2021-12-30'),
                'status' => 'Completed',
                'is_featured' => true,
                'is_active' => true,
                'order' => 1,
            ],
            [
                'title' => 'Construction of 100 & 60 Tonne Dumper Maintenance Sheds',
                'slug' => 'sccl-dumper-maintenance-sheds',
                'description' => 'Construction of maintenance and repair sheds for heavy dumpers at SCCL RG OCP-III.',
                'full_description' => 'Construction of 100 Tonne Dumper maintenance and repair shed (12 bays) and 60 Tonne Dumper maintenance and repair shed (10 bays) with oil room, service rooms, rest hall etc for RG OCP-III, Phase-II, RG-II area, Godavarikhani.',
                'client' => 'The Singareni Collieries Company Ltd',
                'location' => 'Godavarikhani, Peddapalli District, Telangana',
                'category' => 'Industrial Structures',
                'value' => 760.30,
                'start_date' => Carbon::parse('2021-03-01'),
                'end_date' => Carbon::parse('2022-10-31'),
                'status' => 'Completed',
                'is_featured' => true,
                'is_active' => true,
                'order' => 2,
            ],
            [
                'title' => 'Construction of Skew Type Double Lane Road Bridge',
                'slug' => 'sccl-gorrepeta-bridge',
                'description' => '13 vents of 9.50m span bridge across Gorrepeta vagu on approach road to KPUG mine.',
                'full_description' => 'Construction of Skew Type Double Lane Road Bridge (13 vents of 9.50 m span) across Gorrepeta vagu on approach road to KPUG mine, Manuguru Area, Bhadradri Kothagudem District.',
                'client' => 'Singareni Collieries Company Limited',
                'location' => 'Manuguru Area, Bhadradri Kothagudem, Telangana',
                'category' => 'Civil Works',
                'value' => 750.93,
                'start_date' => Carbon::parse('2021-06-01'),
                'end_date' => Carbon::parse('2023-03-31'),
                'status' => 'Completed',
                'is_featured' => true,
                'is_active' => true,
                'order' => 3,
            ],
            [
                'title' => 'Additional Electrical Works Phase-II at HPCL',
                'slug' => 'hpcl-additional-electrical-phase-2',
                'description' => 'Additional electrical works Phase-II for HPCL Green R&D Centre, Bangalore.',
                'full_description' => 'Comprehensive additional electrical works Phase-II including power distribution, lighting systems, control panels, and safety systems for HPCL Green R&D Centre.',
                'client' => 'Hindustan Petroleum Corporation Limited',
                'location' => 'Bengaluru, Karnataka',
                'category' => 'Electrical Works',
                'value' => 599.62,
                'start_date' => Carbon::parse('2021-09-01'),
                'end_date' => Carbon::parse('2023-06-30'),
                'status' => 'Completed',
                'is_featured' => true,
                'is_active' => true,
                'order' => 4,
            ],
            [
                'title' => 'Construction of New Building for Nagarjuna Degree College',
                'slug' => 'nagarjuna-degree-college-building',
                'description' => 'Construction of new building comprising of 30 rooms for Nagarjuna Degree College.',
                'full_description' => 'Complete construction of new academic building with 30 rooms including classrooms, laboratories, and administrative facilities for Nagarjuna Degree College at Nalgonda District.',
                'client' => 'Telangana State Education Welfare Infrastructure Development Corporation (TSEWIDC)',
                'location' => 'Nalgonda District, Telangana',
                'category' => 'Institutional Buildings',
                'value' => 573.43,
                'start_date' => Carbon::parse('2020-04-01'),
                'end_date' => Carbon::parse('2022-03-31'),
                'status' => 'Completed',
                'is_featured' => false,
                'is_active' => true,
                'order' => 5,
            ],
            [
                'title' => 'Construction of Compound Wall and Security Building',
                'slug' => 'hpcl-compound-wall-security',
                'description' => 'Construction of compound wall and security building for 50 acres land at HPCL.',
                'full_description' => 'Complete construction of perimeter compound wall and security building infrastructure for 50 acres land at HPCL Green R&D Centre, Bangalore.',
                'client' => 'Hindustan Petroleum Corporation Limited',
                'location' => 'Bengaluru, Karnataka',
                'category' => 'Civil Works',
                'value' => 546.39,
                'start_date' => Carbon::parse('2019-06-01'),
                'end_date' => Carbon::parse('2020-12-31'),
                'status' => 'Completed',
                'is_featured' => false,
                'is_active' => true,
                'order' => 6,
            ],
            [
                'title' => 'Annual Civil Maintenance Works at NTPC Ramagundam',
                'slug' => 'ntpc-annual-civil-maintenance',
                'description' => 'Annual civil maintenance works in OFFSITE plant area at Ramagundam STPS for 2023-24.',
                'full_description' => 'Comprehensive annual civil maintenance works including repairs, renovations, and upkeep of civil infrastructure in OFFSITE plant area at Ramagundam Super Thermal Power Station.',
                'client' => 'NTPC Limited',
                'location' => 'Ramagundam, Telangana',
                'category' => 'Civil Works',
                'value' => 444.52,
                'start_date' => Carbon::parse('2023-04-01'),
                'end_date' => Carbon::parse('2024-03-31'),
                'status' => 'Completed',
                'is_featured' => false,
                'is_active' => true,
                'order' => 7,
            ],
            [
                'title' => 'Laying of CC Roads at Various Places in Bhongir',
                'slug' => 'bhongir-cc-roads',
                'description' => 'Laying of cement concrete roads at various places in Bhongir Municipality.',
                'full_description' => 'Construction of cement concrete roads at various locations in Bhongir Municipality including drainage systems and road infrastructure development.',
                'client' => 'SE, TUFIDC UNIT II',
                'location' => 'Bhongir, Nalgonda District, Telangana',
                'category' => 'Infrastructure Development',
                'value' => 437.27,
                'start_date' => Carbon::parse('2021-01-15'),
                'end_date' => Carbon::parse('2022-06-30'),
                'status' => 'Completed',
                'is_featured' => false,
                'is_active' => true,
                'order' => 8,
            ],
            [
                'title' => 'External Electrical Works for THE CLASSE Residential Project',
                'slug' => 'the-classe-external-electrical',
                'description' => 'Complete external electrical works including transformer, switchgear, DG set, and UPS systems.',
                'full_description' => 'Supply, construction, fabrication, installation, testing, commissioning of external electrical works including 33KV transformer, switchgear, DG set, MV cables, rising mains, bus ducts, prepaid energy meters, and UPS distribution for 4 blocks residential building at THE CLASSE, Kokapet.',
                'client' => 'DSR-DSRLS Projects',
                'location' => 'Kokapet, Hyderabad',
                'category' => 'Electrical Works',
                'value' => 921.83,
                'start_date' => Carbon::parse('2022-03-01'),
                'end_date' => Carbon::parse('2024-01-31'),
                'status' => 'Completed',
                'is_featured' => true,
                'is_active' => true,
                'order' => 9,
            ],
            [
                'title' => 'Internal Electrical Works for THE CLASSE Block-B&C',
                'slug' => 'the-classe-internal-electrical',
                'description' => 'Total internal electrical works for Block-B&C at THE CLASSE residential project.',
                'full_description' => 'Supply and erection of complete internal electrical works for Block-B&C including wiring, fixtures, distribution boards, and electrical fittings for THE CLASSE residential project at Kokapet.',
                'client' => 'DSR-DSRLS Projects',
                'location' => 'Kokapet, Hyderabad',
                'category' => 'Electrical Works',
                'value' => 427.00,
                'start_date' => Carbon::parse('2022-06-01'),
                'end_date' => Carbon::parse('2023-12-31'),
                'status' => 'Completed',
                'is_featured' => false,
                'is_active' => true,
                'order' => 10,
            ],
            [
                'title' => 'Construction of Internal CC Drains in Bhongir',
                'slug' => 'bhongir-cc-drains',
                'description' => 'Construction of internal cement concrete drains at various places in Bhongir Municipality.',
                'full_description' => 'Complete construction of internal cement concrete drainage system at various locations in Bhongir Municipality for effective stormwater management.',
                'client' => 'SE, TUFIDC UNIT II',
                'location' => 'Bhongir, Nalgonda District, Telangana',
                'category' => 'Infrastructure Development',
                'value' => 416.01,
                'start_date' => Carbon::parse('2020-09-01'),
                'end_date' => Carbon::parse('2021-12-31'),
                'status' => 'Completed',
                'is_featured' => false,
                'is_active' => true,
                'order' => 11,
            ],
            [
                'title' => 'PSU - Electrical & Instrumentation Works at HPCL',
                'slug' => 'hpcl-psu-electrical-inst',
                'description' => 'PSU electrical and instrumentation works at HPCL Green R&D Centre.',
                'full_description' => 'Complete electrical and instrumentation works for PSU (Process Safety Unit) including control systems, instrumentation, and electrical infrastructure at HPCL Bengaluru.',
                'client' => 'Hindustan Petroleum Corporation Limited',
                'location' => 'Bengaluru, Karnataka',
                'category' => 'Electrical Works',
                'value' => 350.00,
                'start_date' => Carbon::parse('2022-01-01'),
                'end_date' => Carbon::parse('2023-06-30'),
                'status' => 'Completed',
                'is_featured' => false,
                'is_active' => true,
                'order' => 12,
            ],

            // ==================== WORKS ON HAND (ONGOING PROJECTS) ====================

            // Featured Ongoing Projects
            [
                'title' => 'Construction of Two-Lane ROB at L.C.No. 60',
                'slug' => 'warangal-rob-construction',
                'description' => 'Construction of two-lane Road Over Bridge in lieu of level crossing at Warangal.',
                'full_description' => 'Construction of two-lane ROB in lieu of L.C.No. 60 at Railway km 369/14-16 of Kazipet–Vijayawada section and at Km 0/8-10 of Fathimanagar - Mamnur Road in Warangal District.',
                'client' => 'Superintending Engineer (R&B) Warangal Circle',
                'location' => 'Warangal District, Telangana',
                'category' => 'Infrastructure Development',
                'value' => 2799.13,
                'start_date' => Carbon::parse('2023-06-01'),
                'end_date' => Carbon::parse('2025-12-31'),
                'status' => 'In Progress',
                'is_featured' => true,
                'is_active' => true,
                'order' => 13,
            ],
            [
                'title' => 'Establishment of 100 Bedded Mother and Child Hospital',
                'slug' => 'narayanpet-hospital-construction',
                'description' => 'Construction of 100 bedded mother and child hospital centre at Narayanpet.',
                'full_description' => 'Complete establishment of 100 bedded mother and child hospital centre including all medical infrastructure, equipment installation, and support facilities at Narayanpet Mandal.',
                'client' => 'TSMSIDC',
                'location' => 'Narayanpet Mandal, Narayanpet District, Telangana',
                'category' => 'Institutional Buildings',
                'value' => 2611.99,
                'start_date' => Carbon::parse('2023-09-01'),
                'end_date' => Carbon::parse('2025-09-30'),
                'status' => 'In Progress',
                'is_featured' => true,
                'is_active' => true,
                'order' => 14,
            ],
            [
                'title' => 'Construction of 112 Nos. B Type Quarters for NTPC',
                'slug' => 'ntpc-b-type-quarters',
                'description' => 'Construction of 112 numbers B Type residential quarters for NTPC Ramagundam.',
                'full_description' => 'Complete construction of 112 numbers B Type residential quarters for NTPC employees at Ramagundam, Telangana Stage-I 2x800 MW project including all amenities and infrastructure.',
                'client' => 'Shradha Saboori Projects India Pvt. Ltd.',
                'location' => 'Ramagundam, Telangana',
                'category' => 'Institutional Buildings',
                'value' => 2264.40,
                'start_date' => Carbon::parse('2023-04-01'),
                'end_date' => Carbon::parse('2025-06-30'),
                'status' => 'In Progress',
                'is_featured' => true,
                'is_active' => true,
                'order' => 15,
            ],
            [
                'title' => 'Construction of Building and Infrastructure for NG Degree College',
                'slug' => 'ng-degree-college-nalgonda',
                'description' => 'Construction of building and infrastructure facilities for NG Degree College at Nalgonda.',
                'full_description' => 'Complete construction of academic building and infrastructure facilities including classrooms, laboratories, library, administrative block, and support facilities for NG Degree College at Nalgonda Town & District.',
                'client' => 'Telangana State Education Welfare Infrastructure Development Corporation (TSEWIDC)',
                'location' => 'Nalgonda Town & District, Telangana',
                'category' => 'Institutional Buildings',
                'value' => 2011.93,
                'start_date' => Carbon::parse('2023-07-01'),
                'end_date' => Carbon::parse('2025-12-31'),
                'status' => 'In Progress',
                'is_featured' => true,
                'is_active' => true,
                'order' => 16,
            ],
            [
                'title' => 'Double Lane Road from Rudraram to PWD Road',
                'slug' => 'rudraram-double-lane-road',
                'description' => 'Construction of double lane road from Rudraram to PWD Road via Gottigakalan.',
                'full_description' => 'Construction of double lane road from Rudraram to PWD Road at Gottigakurd via Gottigakalan & Patimeedipalli in Ranga Reddy District.',
                'client' => 'SE (PR) Circle, Ranga Reddy RO, PRED, Rangareddy',
                'location' => 'Ranga Reddy District, Telangana',
                'category' => 'Infrastructure Development',
                'value' => 1788.31,
                'start_date' => Carbon::parse('2024-01-01'),
                'end_date' => Carbon::parse('2025-12-31'),
                'status' => 'In Progress',
                'is_featured' => false,
                'is_active' => true,
                'order' => 17,
            ],
            [
                'title' => 'Internal Electrical Works for Vasavi Atlantis Towers',
                'slug' => 'vasavi-atlantis-electrical',
                'description' => 'Supply and installation of internal electrical works for Vasavi Atlantis project towers.',
                'full_description' => 'Supply of wire, consumables, installation, testing and commissioning of internal electrical works for Vasavi Atlantis project Tower-1, 2, 3 & 5 at Narsingi, Hyderabad.',
                'client' => 'Vasavi Constructions LLP',
                'location' => 'Narsingi, Hyderabad',
                'category' => 'Electrical Works',
                'value' => 1680.82,
                'start_date' => Carbon::parse('2023-10-01'),
                'end_date' => Carbon::parse('2025-06-30'),
                'status' => 'In Progress',
                'is_featured' => false,
                'is_active' => true,
                'order' => 18,
            ],
            [
                'title' => 'Construction of HLBs and Road from Nagasamundar to Bomraspet',
                'slug' => 'nagasamundar-road-construction',
                'description' => 'Construction of high level bridges and road from Nagasamundar to Bomraspet.',
                'full_description' => 'Construction of HLBs and road from Nagasamundar to Bomraspet via Devenoor, Dubbadi (T), Mahnthipur & Janakampally in Ranga Reddy District.',
                'client' => 'SE (PR) Circle, Ranga Reddy RO, PRED, Rangareddy',
                'location' => 'Ranga Reddy District, Telangana',
                'category' => 'Infrastructure Development',
                'value' => 1653.21,
                'start_date' => Carbon::parse('2024-02-01'),
                'end_date' => Carbon::parse('2026-01-31'),
                'status' => 'In Progress',
                'is_featured' => false,
                'is_active' => true,
                'order' => 19,
            ],
            [
                'title' => 'Construction of Club House at The Marquise',
                'slug' => 'the-marquise-club-house',
                'description' => 'Construction of club house project civil and structural works at Kokapet.',
                'full_description' => 'Complete civil and structural works for club house project at The Marquise, Kokapet, Hyderabad including all amenities and facilities.',
                'client' => 'Sri Srinivasa Infra',
                'location' => 'Kokapet, Hyderabad',
                'category' => 'Institutional Buildings',
                'value' => 858.00,
                'start_date' => Carbon::parse('2024-03-01'),
                'end_date' => Carbon::parse('2025-09-30'),
                'status' => 'In Progress',
                'is_featured' => false,
                'is_active' => true,
                'order' => 20,
            ],
            [
                'title' => 'Internal Electrification Works for Vasavi Atlantis',
                'slug' => 'vasavi-atlantis-internal-electrical',
                'description' => 'Internal electrification works for Vasavi Atlantis residential project at Narsingi.',
                'full_description' => 'Complete internal electrification works including wiring, fixtures, distribution systems, and electrical fittings for Vasavi Atlantis residential project.',
                'client' => 'Vasavi Constructions LLP',
                'location' => 'Narsingi, Hyderabad',
                'category' => 'Electrical Works',
                'value' => 688.19,
                'start_date' => Carbon::parse('2023-11-01'),
                'end_date' => Carbon::parse('2025-05-31'),
                'status' => 'In Progress',
                'is_featured' => false,
                'is_active' => true,
                'order' => 21,
            ],
            [
                'title' => 'Construction of HLB from Muttapuram to Dongathogu',
                'slug' => 'muttapuram-hlb-construction',
                'description' => 'Construction of high level bridge on road from Muttapuram to Dongathogu.',
                'full_description' => 'Construction of HLB on road from Muttapuram to Dongathogu at Km 0/850 in Gundala Mandal, Bhadradri Kothagudem District.',
                'client' => 'SE R&B Circle, Khammam',
                'location' => 'Bhadradri Kothagudem District, Telangana',
                'category' => 'Infrastructure Development',
                'value' => 634.24,
                'start_date' => Carbon::parse('2024-01-15'),
                'end_date' => Carbon::parse('2025-12-31'),
                'status' => 'In Progress',
                'is_featured' => false,
                'is_active' => true,
                'order' => 22,
            ],
            [
                'title' => 'Construction of Roads and Drains in PTS NTPC',
                'slug' => 'ntpc-roads-drains',
                'description' => 'Construction of roads and drainage systems in PTS NTPC Telangana Phase I.',
                'full_description' => 'Complete construction of internal roads and drainage systems for NTPC Telangana Phase I project at Ramagundam.',
                'client' => 'NTPC Limited',
                'location' => 'Ramagundam, Telangana',
                'category' => 'Infrastructure Development',
                'value' => 551.30,
                'start_date' => Carbon::parse('2023-08-01'),
                'end_date' => Carbon::parse('2025-03-31'),
                'status' => 'In Progress',
                'is_featured' => false,
                'is_active' => true,
                'order' => 23,
            ],
            [
                'title' => 'Upgradation of Primary Health Centre at Kowdipally',
                'slug' => 'kowdipally-phc-upgradation',
                'description' => 'Upgradation of PHC from 6 bedded to 50 bedded hospital at Kowdipally Village.',
                'full_description' => 'Upgradation of Primary Health Centre at Kowdipally Village, Narsapur, Medak District from 6 bedded to 50 bedded hospital including all medical infrastructure and facilities.',
                'client' => 'Managing Director, TSMSIDC',
                'location' => 'Kowdipally Village, Narsapur, Medak District, Telangana',
                'category' => 'Institutional Buildings',
                'value' => 547.15,
                'start_date' => Carbon::parse('2023-12-01'),
                'end_date' => Carbon::parse('2025-06-30'),
                'status' => 'In Progress',
                'is_featured' => false,
                'is_active' => true,
                'order' => 24,
            ],
        ];

        foreach ($projects as $project) {
            Project::create($project);
        }

        $this->command->info('Projects seeded successfully! Total: ' . count($projects) . ' projects');
        $this->command->info('Completed Projects: ' . collect($projects)->where('status', 'Completed')->count());
        $this->command->info('Ongoing Projects: ' . collect($projects)->where('status', 'In Progress')->count());
    }
}
